version: "3"
networks:
    network:
        name: "chat-network"
        ipam:
            config:
                - subnet: 10.56.67.0/24
                  gateway: 10.56.67.1
services:
#    golang:
#      container_name: "idc-golang-${APP_ID}"
#      image: golang:alpine
#      working_dir: /go/src/
#      # command: ["go", "mod", "tidy"]
#      # command: ["go", "install", "github.com/pilu/fresh@latest"]
#      ports:
#        - "${SERVER_PORT}:${SERVER_PORT}"
#      stdin_open: true
#      tty: true
#      tty: true
#      volumes:
#          - ./server:/go/src/
#      networks:
#        network:
#            ipv4_address: 10.66.67.3
#      restart: always
    nginx:
        container_name: "idc-nginx"
        image: "nginx:alpine"
        ports:
            - "3001:3001"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./admin/dist:/var/www/dist
        environment:
            TZ: "Asia/Shanghai"
        networks:
            network:
                ipv4_address: 10.56.67.7
        restart:
            always
#    mysql:
#        container_name: "idc-mysql"
#        image: "mysql:8.0.19"
#        platform: linux/x86_64
#        ports:
#            - "23306:3306"
#        environment:
#            TZ: "Asia/Shanghai"
#            MYSQL_ROOT_PASSWORD: idc123456
#            MYSQL_DATABASE: idc
#            MYSQL_USER: idc
#            MYSQL_PASSWORD: 123456
#        volumes:
#            - ./sql:/docker-entrypoint-initdb.d/
#            - ./docker/mysql/conf.d:/etc/mysql/conf.d
#            - ./docker/mysql/data:/var/lib/mysql
#            - ./docker/mysql/logs:/logs
#            - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
#        command:
#            --lower-case-table-names=1
#            --character-set-server=utf8mb4
#            --collation-server=utf8mb4_general_ci
#            --explicit_defaults_for_timestamp=true
#        networks:
#            network:
#                ipv4_address: 10.56.67.8
#        restart: always
#    redis:
#        container_name: "idc-redis"
#        image: redis
#        ports:
#            - "36379:6379"
#        command: "--requirepass idc123456"
#        privileged: true
#        environment:
#            TZ: "Asia/Shanghai"
#        networks:
#            network:
#                ipv4_address: 10.56.67.10
#        restart: always
#    webssh:
#        container_name: "idc-webssh"
#        image: "jrohy/webssh"
#        ports:
#            - "5032:5032"
#        volumes:
#            - /etc/localtime:/etc/localtime
#        environment:
#            TZ: "Asia/Shanghai"
#        networks:
#            network:
#                ipv4_address: 10.56.67.12
#        restart: unless-stopped
